import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';
import api from '@/api';

export interface Service {
  id: string;
  title: string;
  description: string;
  price: string;
  duration: string;
  rating: number;
  patients: number;
  isPopular?: boolean;
  category: string;
  imageAlt: string;
  image?: string;
  detailedDescription?: string;
  additionalImages?: string[];
  features?: string[];
  requirements?: string[];
}

interface ServiceContextType {
  services: Service[];
  addService: (service: Omit<Service, 'id'>) => void;
  updateService: (id: string, service: Partial<Service>) => void;
  deleteService: (id: string) => void;
  getService: (id: string) => Service | undefined;
  updateOffer: (id: string, offer: Partial<Service>) => void;
  deleteOffer: (id: string) => void;
}

const ServiceContext = createContext<ServiceContextType | undefined>(undefined);

const initialServices: Service[] = [
  {
    id: "1",
    title: "Aarogyam Winter Basic with USTSH",
    description: "Aarogyam Winter Basic with UTSH is a preventive care package of 68 parameters for overall health checkup. It evaluates the health of the liver and kidneys as well as measures lipids, electrolytes, like sodium and chloride, and iron levels using a blood sample. It also includes CBC, ultrasensitive TSH and tests for detecting diabetes and assessing vitamin D and B-12 levels. Regular health checkups help in the early diagnosis of health problems.",
    price: "1399",
    duration: "15 min",
    rating: 4.8,
    patients: 1250,
    isPopular: true,
    category: "Winter",
    imageAlt: "Internal Medicine Doctor Photo",
    detailedDescription: "Aarogyam Winter Basic with UTSH is a preventive care package of 68 parameters for overall health checkup. It evaluates the health of the liver and kidneys as well as measures lipids, electrolytes, like sodium and chloride, and iron levels using a blood sample. It also includes CBC, ultrasensitive TSH and tests for detecting diabetes and assessing vitamin D and B-12 levels. Regular health checkups help in the early diagnosis of health problems.",
    features: [
      "CHLORIDE",
      "SODIUM",
      "TSH - ULTRASENSITIVE",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "ALKALINE PHOSPHATASE",
      "BILIRUBIN -DIRECT",
      "BILIRUBIN (INDIRECT)",
      "BILIRUBIN - TOTAL",
      "GAMMA GLUTAMYL TRANSFERASE (GGT)",
      "SGOT / SGPT RATIO",
      "SERUM ALB/GLOBULIN RATIO",
      "PROTEIN - TOTAL",
      "ALBUMIN - SERUM",
      "SERUM GLOBULIN",
      "ASPARTATE AMINOTRANSFERASE (SGOT )",
      "ALANINE TRANSAMINASE (SGPT)",
      "IRON",
      "% TRANSFERRIN SATURATION",
      "TOTAL IRON BINDING CAPACITY (TIBC)",
      "UNSAT.IRON-BINDING CAPACITY(UIBC)",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "25-OH VITAMIN D (TOTAL)",
      "VITAMIN B-12"
    ],
    requirements: ["Valid ID", "Insurance information", "Medical history"]
  },
  // {
  //   id: '2',
  //   title: "Dermatology",
  //   description: "From skin problems like eczema, atopic dermatitis, acne to cosmetic dermatology, specialists will provide treatment.",
  //   price: "$35",
  //   duration: "20 min",
  //   rating: 4.9,
  //   patients: 890,
  //   category: "Dermatology",
  //   imageAlt: "Dermatology Specialist Photo",
  //   detailedDescription: "Expert dermatological care for all skin conditions. Our specialists use the latest treatments and technologies to ensure optimal skin health.",
  //   features: ["Skin cancer screening", "Acne treatment", "Cosmetic procedures", "Skin allergy testing"],
  //   requirements: ["Clean skin (no makeup)", "List of current medications", "Medical history"]
  // },
  // {
  //   id: '3',
  //   title: "Psychiatry",
  //   description: "Specialists provide counseling for mental health issues such as depression, anxiety disorders, and panic disorders.",
  //   price: "$50",
  //   duration: "30 min",
  //   rating: 4.7,
  //   patients: 670,
  //   category: "Psychiatry",
  //   imageAlt: "Psychiatrist Photo",
  //   detailedDescription: "Professional mental health support with compassionate care. We provide therapy and medication management for various mental health conditions.",
  //   features: ["Individual therapy", "Medication management", "Crisis intervention", "Treatment planning"],
  //   requirements: ["Insurance verification", "Emergency contact", "Previous therapy records if available"]
  // },
  // {
  //   id: '4',
  //   title: "Pediatrics",
  //   description: "From children's symptoms like fever, cough, rash to vaccination consultations, pediatric specialists will respond.",
  //   price: "$28",
  //   duration: "15 min",
  //   rating: 4.9,
  //   patients: 1100,
  //   isPopular: true,
  //   category: "Pediatrics",
  //   imageAlt: "Pediatrician Photo",
  //   detailedDescription: "Specialized healthcare for infants, children, and adolescents. Our pediatricians focus on the physical, mental, and social health of children.",
  //   features: ["Well-child visits", "Vaccinations", "Growth monitoring", "Developmental assessments"],
  //   requirements: ["Guardian present", "Vaccination records", "Growth chart if available"]
  // },
  // {
  //   id: '5',
  //   title: "Gynecology",
  //   description: "Specialists will examine women's specific concerns such as menstrual irregularities, menopause, and pregnancy-related consultations.",
  //   price: "$40",
  //   duration: "25 min",
  //   rating: 4.8,
  //   patients: 750,
  //   category: "Gynecology",
  //   imageAlt: "Gynecologist Photo",
  //   detailedDescription: "Comprehensive women's health services including routine gynecological care, family planning, and specialized treatments.",
  //   features: ["Annual exams", "Family planning", "Pregnancy care", "Menopause management"],
  //   requirements: ["Medical history", "Last menstrual period date", "Insurance information"]
  // },
  // {
  //   id: '6',
  //   title: "Orthopedics",
  //   description: "Specialists provide advice on orthopedic symptoms such as stiff shoulders, back pain, and joint pain.",
  //   price: "$38",
  //   duration: "20 min",
  //   rating: 4.6,
  //   patients: 580,
  //   category: "Orthopedics",
  //   imageAlt: "Orthopedic Doctor Photo",
  //   detailedDescription: "Expert care for bones, joints, and muscles. Our orthopedic specialists treat injuries and conditions affecting the musculoskeletal system.",
  //   features: ["Injury assessment", "Joint replacement", "Sports medicine", "Physical therapy referrals"],
  //   requirements: ["X-rays if available", "Pain level assessment", "Activity limitations list"]
  // },
  // {
  //   id: '7',
  //   title: "Ophthalmology",
  //   description: "Specialists will examine ophthalmologic symptoms such as eye pain, vision loss, and dry eyes.",
  //   price: "$32",
  //   duration: "15 min",
  //   rating: 4.7,
  //   patients: 420,
  //   category: "Eye Care",
  //   imageAlt: "Ophthalmologist Photo",
  //   detailedDescription: "Complete eye care services including routine eye exams, vision correction, and treatment of eye diseases.",
  //   features: ["Eye exams", "Vision testing", "Glaucoma screening", "Contact lens fitting"],
  //   requirements: ["Current glasses/contacts", "Eye symptom history", "Insurance card"]
  // },
  // {
  //   id: '8',
  //   title: "ENT (Ear, Nose, Throat)",
  //   description: "Specialists provide ENT treatment for symptoms such as sore throat, nasal congestion, and ear symptoms.",
  //   price: "$33",
  //   duration: "18 min",
  //   rating: 4.5,
  //   patients: 350,
  //   category: "ENT",
  //   imageAlt: "ENT Specialist Photo",
  //   detailedDescription: "Specialized care for ear, nose, and throat conditions. Our ENT specialists diagnose and treat a wide range of conditions.",
  //   features: ["Hearing tests", "Sinus treatment", "Throat procedures", "Allergy management"],
  //   requirements: ["Symptom timeline", "Allergy information", "Previous treatments tried"]
  // },
  // New blank cards start here
  {
    id: "9",
    title: "COMPLETE HEALTH CHECK WITH VITAMINS",
    description: "Complete Health Check with Vitamins is a full-body health checkup package that consists of 122 tests that cover crucial health parameters. Stay ahead of underlying health conditions.",
    price: "1999",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Complete Health Check with Vitamins is a full-body health checkup package that consists of 122 tests that cover crucial health parameters. Stay ahead of underlying health conditions.",
    features: [
      "CARCINO EMBRYONIC ANTIGEN (CEA)",
      "CHLORIDE",
      "HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)",
      "Lipoprotein (a) [Lp(a)]",
      "SODIUM",
      "SPECIFIC GRAVITY",
      "APPEARANCE",
      "BACTERIA",
      "URINARY BILIRUBIN",
      "URINE BLOOD",
      "UROBILINOGEN",
      "BILE PIGMENT",
      "BILE SALT",
      "CASTS",
      "COLOUR",
      "CRYSTALS",
      "EPITHELIAL CELLS",
      "URINARY GLUCOSE",
      "URINE KETONE",
      "LEUCOCYTE ESTERASE",
      "URINARY LEUCOCYTES (PUS CELLS)",
      "MUCUS",
      "NITRITE",
      "PARASITE",
      "PH",
      "URINARY PROTEIN",
      "RED BLOOD CELLS",
      "VOLUME",
      "YEAST",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "ALKALINE PHOSPHATASE",
      "BILIRUBIN -DIRECT",
      "BILIRUBIN (INDIRECT)",
      "BILIRUBIN - TOTAL",
      "GAMMA GLUTAMYL TRANSFERASE (GGT)",
      "SGOT / SGPT RATIO",
      "SERUM ALB/GLOBULIN RATIO",
      "PROTEIN - TOTAL",
      "ALBUMIN - SERUM",
      "SERUM GLOBULIN",
      "ASPARTATE AMINOTRANSFERASE (SGOT )",
      "ALANINE TRANSAMINASE (SGPT)",
      "SILVER",
      "ALUMINIUM",
      "ARSENIC",
      "BARIUM",
      "BERYLLIUM",
      "BISMUTH",
      "CADMIUM",
      "COBALT",
      "CHROMIUM",
      "CAESIUM",
      "MERCURY",
      "MANGANESE",
      "MOLYBDENUM",
      "NICKEL",
      "LEAD",
      "ANTIMONY",
      "SELENIUM",
      "TIN",
      "STRONTIUM",
      "THALLIUM",
      "URANIUM",
      "VANADIUM",
      "IRON",
      "% TRANSFERRIN SATURATION",
      "TOTAL IRON BINDING CAPACITY (TIBC)",
      "UNSAT.IRON-BINDING CAPACITY(UIBC)",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "25-OH VITAMIN D (TOTAL)",
      "VITAMIN B-12",
      "APO B / APO A1 RATIO (APO B/A1)",
      "APOLIPOPROTEIN - A1 (APO-A1)",
      "APOLIPOPROTEIN - B (APO-B)"
    ],
    requirements: []
  },
  {
    id: "10",
    title: "SENIOR CITIZEN PROFILE MALE",
    description: "The Senior Citizen Profile Male is a health checkup package designed for elderly men to assess overall health. This profile includes 127 crucial tests for vital organ functions.",
    price: "2399",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "The Senior Citizen Profile Male is a health checkup package designed for elderly men to assess overall health. This profile includes 127 crucial tests for vital organ functions.",
    features: [
      "FASTING BLOOD SUGAR(GLUCOSE)",
      "CARCINO EMBRYONIC ANTIGEN (CEA)",
      "CHLORIDE",
      "25-OH VITAMIN D (TOTAL)",
      "FERRITIN",
      "HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)",
      "LIPASE",
      "Lipoprotein (a) [Lp(a)]",
      "PROSTATE SPECIFIC ANTIGEN (PSA)",
      "SODIUM",
      "VITAMIN B-12",
      "SPECIFIC GRAVITY",
      "APPEARANCE",
      "BACTERIA",
      "URINARY BILIRUBIN",
      "URINE BLOOD",
      "UROBILINOGEN",
      "BILE PIGMENT",
      "BILE SALT",
      "CASTS",
      "COLOUR",
      "CRYSTALS",
      "EPITHELIAL CELLS",
      "URINARY GLUCOSE",
      "URINE KETONE",
      "LEUCOCYTE ESTERASE",
      "URINARY LEUCOCYTES (PUS CELLS)",
      "MUCUS",
      "NITRITE",
      "PARASITE",
      "PH",
      "URINARY PROTEIN",
      "RED BLOOD CELLS",
      "VOLUME",
      "YEAST",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "ALKALINE PHOSPHATASE",
      "BILIRUBIN -DIRECT",
      "BILIRUBIN (INDIRECT)",
      "BILIRUBIN - TOTAL",
      "GAMMA GLUTAMYL TRANSFERASE (GGT)",
      "SGOT / SGPT RATIO",
      "SERUM ALB/GLOBULIN RATIO",
      "PROTEIN - TOTAL",
      "ALBUMIN - SERUM",
      "SERUM GLOBULIN",
      "ASPARTATE AMINOTRANSFERASE (SGOT )",
      "ALANINE TRANSAMINASE (SGPT)",
      "SILVER",
      "ALUMINIUM",
      "ARSENIC",
      "BARIUM",
      "BERYLLIUM",
      "BISMUTH",
      "CADMIUM",
      "COBALT",
      "CHROMIUM",
      "CAESIUM",
      "MERCURY",
      "MANGANESE",
      "MOLYBDENUM",
      "NICKEL",
      "LEAD",
      "ANTIMONY",
      "SELENIUM",
      "TIN",
      "STRONTIUM",
      "THALLIUM",
      "URANIUM",
      "VANADIUM",
      "IRON",
      "% TRANSFERRIN SATURATION",
      "TOTAL IRON BINDING CAPACITY (TIBC)",
      "UNSAT.IRON-BINDING CAPACITY(UIBC)",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "TOTAL TRIIODOTHYRONINE (T3)",
      "TOTAL THYROXINE (T4)",
      "TSH - ULTRASENSITIVE",
      "APO B / APO A1 RATIO (APO B/A1)",
      "APOLIPOPROTEIN - A1 (APO-A1)",
      "APOLIPOPROTEIN - B (APO-B)",
      "AMYLASE"
    ],
    requirements: []
  },
  {
    id: "11",
    title: "SENIOR CITIZEN PROFILE FEMALE",
    description: "Senior Citizen Profile Female is a health checkup package for elderly women to assess overall health. Includes vital organ and deficiency tests.",
    price: "2399",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Senior Citizen Profile Female is a health checkup package for elderly women to assess overall health. Includes vital organ and deficiency tests.",
    features: [
      "FASTING BLOOD SUGAR(GLUCOSE)",
      "CA-125",
      "CARCINO EMBRYONIC ANTIGEN (CEA)",
      "CHLORIDE",
      "25-OH VITAMIN D (TOTAL)",
      "FERRITIN",
      "HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)",
      "LIPASE",
      "Lipoprotein (a) [Lp(a)]",
      "SODIUM",
      "VITAMIN B-12",
      "SPECIFIC GRAVITY",
      "APPEARANCE",
      "BACTERIA",
      "URINARY BILIRUBIN",
      "URINE BLOOD",
      "UROBILINOGEN",
      "BILE PIGMENT",
      "BILE SALT",
      "CASTS",
      "COLOUR",
      "CRYSTALS",
      "EPITHELIAL CELLS",
      "URINARY GLUCOSE",
      "URINE KETONE",
      "LEUCOCYTE ESTERASE",
      "URINARY LEUCOCYTES (PUS CELLS)",
      "MUCUS",
      "NITRITE",
      "PARASITE",
      "PH",
      "URINARY PROTEIN",
      "RED BLOOD CELLS",
      "VOLUME",
      "YEAST",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "ALKALINE PHOSPHATASE",
      "BILIRUBIN -DIRECT",
      "BILIRUBIN (INDIRECT)",
      "BILIRUBIN - TOTAL",
      "GAMMA GLUTAMYL TRANSFERASE (GGT)",
      "SGOT / SGPT RATIO",
      "SERUM ALB/GLOBULIN RATIO",
      "PROTEIN - TOTAL",
      "ALBUMIN - SERUM",
      "SERUM GLOBULIN",
      "ASPARTATE AMINOTRANSFERASE (SGOT )",
      "ALANINE TRANSAMINASE (SGPT)",
      "SILVER",
      "ALUMINIUM",
      "ARSENIC",
      "BARIUM",
      "BERYLLIUM",
      "BISMUTH",
      "CADMIUM",
      "COBALT",
      "CHROMIUM",
      "CAESIUM",
      "MERCURY",
      "MANGANESE",
      "MOLYBDENUM",
      "NICKEL",
      "LEAD",
      "ANTIMONY",
      "SELENIUM",
      "TIN",
      "STRONTIUM",
      "THALLIUM",
      "URANIUM",
      "VANADIUM",
      "IRON",
      "% TRANSFERRIN SATURATION",
      "TOTAL IRON BINDING CAPACITY (TIBC)",
      "UNSAT.IRON-BINDING CAPACITY(UIBC)",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "TOTAL TRIIODOTHYRONINE (T3)",
      "TOTAL THYROXINE (T4)",
      "TSH - ULTRASENSITIVE",
      "APO B / APO A1 RATIO (APO B/A1)",
      "APOLIPOPROTEIN - A1 (APO-A1)",
      "APOLIPOPROTEIN - B (APO-B)",
      "AMYLASE"
    ],
    requirements: []
  },
  {
    id: "12",
    title: "Aarogyam C plus with USTSH",
    description: "Aarogyam C with UTSH is an all-inclusive 74-parameter preventive care package for full-body health checkup, including testosterone and vitamin D & B12 analysis.",
    price: "",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Aarogyam C with UTSH is an all-inclusive 74-parameter preventive care package that offers full-body health checkup at a pocket-friendly rate. In addition to all parameters under Aarogyam B with UTSH, this profile includes testosterone and vitamin D & B12 analysis, making it a unique package. It also assesses the functioning of the thyroid, liver and kidneys. CBC helps assess heart functions and diabetes status. Regular preventive health checkups pave way for early detection of health problems.",
    features: [
      "HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)",
      "Lipoprotein (a) [Lp(a)]",
      "TESTOSTERONE",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "ALKALINE PHOSPHATASE",
      "BILIRUBIN -DIRECT",
      "BILIRUBIN (INDIRECT)",
      "BILIRUBIN - TOTAL",
      "GAMMA GLUTAMYL TRANSFERASE (GGT)",
      "SGOT / SGPT RATIO",
      "SERUM ALB/GLOBULIN RATIO",
      "PROTEIN - TOTAL",
      "ALBUMIN - SERUM",
      "SERUM GLOBULIN",
      "ASPARTATE AMINOTRANSFERASE (SGOT )",
      "ALANINE TRANSAMINASE (SGPT)",
      "IRON",
      "% TRANSFERRIN SATURATION",
      "TOTAL IRON BINDING CAPACITY (TIBC)",
      "UNSAT.IRON-BINDING CAPACITY(UIBC)",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "TOTAL TRIIODOTHYRONINE (T3)",
      "TOTAL THYROXINE (T4)",
      "TSH - ULTRASENSITIVE",
      "25-OH VITAMIN D (TOTAL)",
      "VITAMIN B-12",
      "APO B / APO A1 RATIO (APO B/A1)",
      "APOLIPOPROTEIN - A1 (APO-A1)",
      "APOLIPOPROTEIN - B (APO-B)",
    ],
    requirements: []
  },
  {
    id: "13",
    title: "Aarogyam D Plus with USTSH",
    description: "Aarogyam D Plus Profile with UTSH is a complete health checkup package loaded with 114 parameters, including Complete Urine Analysis and Fasting Blood Sugar analysis.",
    price: "5099",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Aarogyam D Plus Profile with UTSH is a complete health checkup package loaded with 114 parameters. The key feature of Aarogyam Plus series is the inclusion of Complete Urine Analysis + Fasting Blood Sugar analysis. Along with Thyroid, Lipid, Liver and Kidney health, this package also evaluates the health and functioning of the heart and pancreas. It also includes CBC, diabetes analysis, vitamins and elements. It is a value-for-money package recommended for all age groups. Regular health checkups identify health issues early and enable timely treatment.",
    features: [
      "FASTING BLOOD SUGAR(GLUCOSE)",
      "CHLORIDE",
      "FERRITIN",
      "FOLATE",
      "FRUCTOSAMINE",
      "HOMOCYSTEINE",
      "HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)",
      "LIPASE",
      "Lipoprotein (a) [Lp(a)]",
      "MAGNESIUM",
      "SERUM COPPER",
      "SERUM ZINC",
      "SODIUM",
      "TESTOSTERONE",
      "SPECIFIC GRAVITY",
      "APPEARANCE",
      "BACTERIA",
      "URINARY BILIRUBIN",
      "URINE BLOOD",
      "UROBILINOGEN",
      "BILE PIGMENT",
      "BILE SALT",
      "CASTS",
      "COLOUR",
      "CRYSTALS",
      "EPITHELIAL CELLS",
      "URINARY GLUCOSE",
      "URINE KETONE",
      "LEUCOCYTE ESTERASE",
      "URINARY LEUCOCYTES (PUS CELLS)",
      "MUCUS",
      "NITRITE",
      "PARASITE",
      "PH",
      "URINARY PROTEIN",
      "RED BLOOD CELLS",
      "VOLUME",
      "YEAST",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "ALKALINE PHOSPHATASE",
      "BILIRUBIN -DIRECT",
      "BILIRUBIN (INDIRECT)",
      "BILIRUBIN - TOTAL",
      "GAMMA GLUTAMYL TRANSFERASE (GGT)",
      "SGOT / SGPT RATIO",
      "SERUM ALB/GLOBULIN RATIO",
      "PROTEIN - TOTAL",
      "ALBUMIN - SERUM",
      "SERUM GLOBULIN",
      "ASPARTATE AMINOTRANSFERASE (SGOT )",
      "ALANINE TRANSAMINASE (SGPT)",
      "IRON",
      "% TRANSFERRIN SATURATION",
      "TOTAL IRON BINDING CAPACITY (TIBC)",
      "UNSAT.IRON-BINDING CAPACITY(UIBC)",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "TOTAL TRIIODOTHYRONINE (T3)",
      "TOTAL THYROXINE (T4)",
      "TSH - ULTRASENSITIVE",
      "25-OH VITAMIN D (TOTAL)",
      "VITAMIN B-12",
      "URINARY MICROALBUMIN",
      "URI. ALBUMIN/CREATININE RATIO (UA/C)",
      "CREATININE - URINE",
      "APO B / APO A1 RATIO (APO B/A1)",
      "APOLIPOPROTEIN - A1 (APO-A1)",
      "APOLIPOPROTEIN - B (APO-B)",
      "AMYLASE",
      "BLOOD KETONE (D3HB)",
    ],
    requirements: []
  },
  {
    id: "14",
    title: "Aarogyam E Plus with USTSH",
    description: "Aarogyam E Plus with UTSH contains 118 parameters, covering cystatin C for kidney health and antitrypsin for lung health, ideal for full-body check.",
    price: "6299",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Aarogyam E Plus with UTSH contains 118 parameters, including the key features Complete Urine Analysis + Fasting Blood Sugar analysis. Its unique aspect is that it covers cystatin C for kidney health and antitrypsin for lung health with accurate diagnosis. It also helps understand if a patient is suffering from arthritis. With lipid, liver, kidney, and thyroid health, the package is ideal for full-body check at best prices.",
    features: [
      "FASTING BLOOD SUGAR(GLUCOSE)",
      "CHLORIDE",
      "CYSTATIN C",
      "FERRITIN",
      "FOLATE",
      "FRUCTOSAMINE",
      "HOMOCYSTEINE",
      "HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)",
      "LIPASE",
      "Lipoprotein (a) [Lp(a)]",
      "MAGNESIUM",
      "SERUM COPPER",
      "SERUM ZINC",
      "SODIUM",
      "TESTOSTERONE",
      "ALPHA-1-ANTITRYPSIN (AAT)",
      "SPECIFIC GRAVITY",
      "APPEARANCE",
      "BACTERIA",
      "URINARY BILIRUBIN",
      "URINE BLOOD",
      "UROBILINOGEN",
      "BILE PIGMENT",
      "BILE SALT",
      "CASTS",
      "COLOUR",
      "CRYSTALS",
      "EPITHELIAL CELLS",
      "URINARY GLUCOSE",
      "URINE KETONE",
      "LEUCOCYTE ESTERASE",
      "URINARY LEUCOCYTES (PUS CELLS)",
      "MUCUS",
      "NITRITE",
      "PARASITE",
      "PH",
      "URINARY PROTEIN",
      "RED BLOOD CELLS",
      "VOLUME",
      "YEAST",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "ANTI CCP (ACCP)",
      "ALKALINE PHOSPHATASE",
      "BILIRUBIN -DIRECT",
      "BILIRUBIN (INDIRECT)",
      "BILIRUBIN - TOTAL",
      "GAMMA GLUTAMYL TRANSFERASE (GGT)",
      "SGOT / SGPT RATIO",
      "SERUM ALB/GLOBULIN RATIO",
      "PROTEIN - TOTAL",
      "ALBUMIN - SERUM",
      "SERUM GLOBULIN",
      "ASPARTATE AMINOTRANSFERASE (SGOT )",
      "ALANINE TRANSAMINASE (SGPT)",
      "IRON",
      "% TRANSFERRIN SATURATION",
      "TOTAL IRON BINDING CAPACITY (TIBC)",
      "UNSAT.IRON-BINDING CAPACITY(UIBC)",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "TOTAL TRIIODOTHYRONINE (T3)",
      "TOTAL THYROXINE (T4)",
      "TSH - ULTRASENSITIVE",
      "25-OH VITAMIN D (TOTAL)",
      "VITAMIN B-12",
      "URINARY MICROALBUMIN",
      "URI. ALBUMIN/CREATININE RATIO (UA/C)",
      "CREATININE - URINE",
      "APO B / APO A1 RATIO (APO B/A1)",
      "APOLIPOPROTEIN - A1 (APO-A1)",
      "APOLIPOPROTEIN - B (APO-B)",
      "AMYLASE",
      "ANTI NUCLEAR ANTIBODIES (ANA)",
      "BLOOD KETONE (D3HB)",
    ],
    requirements: []
  },
  {
    id: "15",
    title: "Aarogyam F Plus with USTSH",
    description: "Aarogyam F Plus with UTSH contains 142 parameters, including Complete Urine Analysis, Fasting Blood Sugar, and Lp-PLA2 for cardiovascular risk.",
    price: "7299",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Aarogyam F Plus with UTSH contains whopping 142 parameters, including the key features Complete Urine Analysis + Fasting Blood Sugar analysis. Along with standard Plus series parameters, this profile contains Lp-PLA2. This helps you understand your risk of cardiovascular diseases and stroke. Insulin analysis helps in accurate diabetes screening. Its unique aspect is that it covers cystatin C for kidney health and antitrypsin for lung health with accurate diagnosis. The package is ideal for full-body check at best prices.",
    features: [
      "FASTING BLOOD SUGAR(GLUCOSE)",
      "CHLORIDE",
      "CYSTATIN C",
      "FERRITIN",
      "FOLATE",
      "FRUCTOSAMINE",
      "HOMOCYSTEINE",
      "HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)",
      "INSULIN - FASTING",
      "LIPASE",
      "Lipoprotein (a) [Lp(a)]",
      "MAGNESIUM",
      "LP-PLA2",
      "SERUM COPPER",
      "SERUM ZINC",
      "SODIUM",
      "TESTOSTERONE",
      "ALPHA-1-ANTITRYPSIN (AAT)",
      "SPECIFIC GRAVITY",
      "APPEARANCE",
      "BACTERIA",
      "URINARY BILIRUBIN",
      "URINE BLOOD",
      "UROBILINOGEN",
      "BILE PIGMENT",
      "BILE SALT",
      "CASTS",
      "COLOUR",
      "CRYSTALS",
      "EPITHELIAL CELLS",
      "URINARY GLUCOSE",
      "URINE KETONE",
      "LEUCOCYTE ESTERASE",
      "URINARY LEUCOCYTES (PUS CELLS)",
      "MUCUS",
      "NITRITE",
      "PARASITE",
      "PH",
      "URINARY PROTEIN",
      "RED BLOOD CELLS",
      "VOLUME",
      "YEAST",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "ANTI CCP (ACCP)",
      "ALKALINE PHOSPHATASE",
      "BILIRUBIN -DIRECT",
      "BILIRUBIN (INDIRECT)",
      "BILIRUBIN - TOTAL",
      "GAMMA GLUTAMYL TRANSFERASE (GGT)",
      "SGOT / SGPT RATIO",
      "SERUM ALB/GLOBULIN RATIO",
      "PROTEIN - TOTAL",
      "ALBUMIN - SERUM",
      "SERUM GLOBULIN",
      "ASPARTATE AMINOTRANSFERASE (SGOT )",
      "ALANINE TRANSAMINASE (SGPT)",
      "SILVER",
      "ALUMINIUM",
      "ARSENIC",
      "BARIUM",
      "BERYLLIUM",
      "BISMUTH",
      "CADMIUM",
      "COBALT",
      "CHROMIUM",
      "CAESIUM",
      "MERCURY",
      "MANGANESE",
      "MOLYBDENUM",
      "NICKEL",
      "LEAD",
      "ANTIMONY",
      "SELENIUM",
      "TIN",
      "STRONTIUM",
      "THALLIUM",
      "URANIUM",
      "VANADIUM",
      "IRON",
      "% TRANSFERRIN SATURATION",
      "TOTAL IRON BINDING CAPACITY (TIBC)",
      "UNSAT.IRON-BINDING CAPACITY(UIBC)",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "TOTAL TRIIODOTHYRONINE (T3)",
      "TOTAL THYROXINE (T4)",
      "TSH - ULTRASENSITIVE",
      "25-OH VITAMIN D (TOTAL)",
      "VITAMIN B-12",
      "APO B / APO A1 RATIO (APO B/A1)",
      "APOLIPOPROTEIN - A1 (APO-A1)",
      "APOLIPOPROTEIN - B (APO-B)",
      "AMYLASE",
      "ANTI NUCLEAR ANTIBODIES (ANA)",
      "BLOOD KETONE (D3HB)",
    ],
    requirements: []
  },
  {
    id: "16",
    title: "Aarogyam Stree Profile with USTSH",
    description: "Aarogyam Stree Profile with UTSH comprises 110 parameters tailor made for a woman, including hormones, cancer markers, bone profile, and more.",
    price: "4399",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Aarogyam Stree Profile with UTSH comprises of 110 parameters tailor made for a woman. It contains Hormones, Cancer Markers, Bone Profile and Complete Urine Analysis along with the all other important parameters for full body check up",
    features: [
      "CA-125",
      "CARCINO EMBRYONIC ANTIGEN (CEA)",
      "CHLORIDE",
      "ESTRADIOL/OESTROGEN (E2)",
      "FOLATE",
      "FOLLICLE STIMULATING HORMONE (FSH)",
      "HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)",
      "LUTEINISING HORMONE (LH)",
      "Lipoprotein (a) [Lp(a)]",
      "MAGNESIUM",
      "PHOSPHOROUS",
      "PROLACTIN (PRL)",
      "SODIUM",
      "TOTAL TRIIODOTHYRONINE (T3)",
      "TOTAL THYROXINE (T4)",
      "TSH - ULTRASENSITIVE",
      "SPECIFIC GRAVITY",
      "APPEARANCE",
      "BACTERIA",
      "URINARY BILIRUBIN",
      "URINE BLOOD",
      "UROBILINOGEN",
      "BILE PIGMENT",
      "BILE SALT",
      "CASTS",
      "COLOUR",
      "CRYSTALS",
      "EPITHELIAL CELLS",
      "URINARY GLUCOSE",
      "URINE KETONE",
      "LEUCOCYTE ESTERASE",
      "URINARY LEUCOCYTES (PUS CELLS)",
      "MUCUS",
      "NITRITE",
      "PARASITE",
      "PH",
      "URINARY PROTEIN",
      "RED BLOOD CELLS",
      "VOLUME",
      "YEAST",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "ANTI CCP (ACCP)",
      "ALKALINE PHOSPHATASE",
      "BILIRUBIN -DIRECT",
      "BILIRUBIN (INDIRECT)",
      "BILIRUBIN - TOTAL",
      "GAMMA GLUTAMYL TRANSFERASE (GGT)",
      "SGOT / SGPT RATIO",
      "SERUM ALB/GLOBULIN RATIO",
      "PROTEIN - TOTAL",
      "ALBUMIN - SERUM",
      "SERUM GLOBULIN",
      "ASPARTATE AMINOTRANSFERASE (SGOT )",
      "ALANINE TRANSAMINASE (SGPT)",
      "IRON",
      "% TRANSFERRIN SATURATION",
      "TOTAL IRON BINDING CAPACITY (TIBC)",
      "UNSAT.IRON-BINDING CAPACITY(UIBC)",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "25-OH VITAMIN D (TOTAL)",
      "VITAMIN B-12",
      "APO B / APO A1 RATIO (APO B/A1)",
      "APOLIPOPROTEIN - A1 (APO-A1)",
      "APOLIPOPROTEIN - B (APO-B)",
      "ANTI NUCLEAR ANTIBODIES (ANA)",
    ],
    requirements: []
  },
  {
    id: "17",
    title: "Aarogyam Purush Profile With USTSH",
    description: "Aarogyam Purush Profile with UTSH comprises 107 parameters tailor made for a man, including hormones, cancer markers, bone profile, and more.",
    price: "4564",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Aarogyam Purush Profile with UTSH comprises of 107 parameters tailor made for a man. It contains Hormones, Cancer Markers, Bone Profile and Complete Urine Analysis along with the all other important parameters for full body check up",
    features: [
      "CARCINO EMBRYONIC ANTIGEN (CEA)",
      "CHLORIDE",
      "FOLATE",
      "HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)",
      "Lipoprotein (a) [Lp(a)]",
      "MAGNESIUM",
      "PHOSPHOROUS",
      "PROSTATE SPECIFIC ANTIGEN (PSA)",
      "SODIUM",
      "TESTOSTERONE",
      "SPECIFIC GRAVITY",
      "APPEARANCE",
      "BACTERIA",
      "URINARY BILIRUBIN",
      "URINE BLOOD",
      "UROBILINOGEN",
      "BILE PIGMENT",
      "BILE SALT",
      "CASTS",
      "COLOUR",
      "CRYSTALS",
      "EPITHELIAL CELLS",
      "URINARY GLUCOSE",
      "URINE KETONE",
      "LEUCOCYTE ESTERASE",
      "URINARY LEUCOCYTES (PUS CELLS)",
      "MUCUS",
      "NITRITE",
      "PARASITE",
      "PH",
      "URINARY PROTEIN",
      "RED BLOOD CELLS",
      "VOLUME",
      "YEAST",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "ANTI CCP (ACCP)",
      "ALKALINE PHOSPHATASE",
      "BILIRUBIN -DIRECT",
      "BILIRUBIN (INDIRECT)",
      "BILIRUBIN - TOTAL",
      "GAMMA GLUTAMYL TRANSFERASE (GGT)",
      "SGOT / SGPT RATIO",
      "SERUM ALB/GLOBULIN RATIO",
      "PROTEIN - TOTAL",
      "ALBUMIN - SERUM",
      "SERUM GLOBULIN",
      "ASPARTATE AMINOTRANSFERASE (SGOT )",
      "ALANINE TRANSAMINASE (SGPT)",
      "IRON",
      "% TRANSFERRIN SATURATION",
      "TOTAL IRON BINDING CAPACITY (TIBC)",
      "UNSAT.IRON-BINDING CAPACITY(UIBC)",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "TOTAL TRIIODOTHYRONINE (T3)",
      "TOTAL THYROXINE (T4)",
      "TSH - ULTRASENSITIVE",
      "25-OH VITAMIN D (TOTAL)",
      "VITAMIN B-12",
      "APO B / APO A1 RATIO (APO B/A1)",
      "APOLIPOPROTEIN - A1 (APO-A1)",
      "APOLIPOPROTEIN - B (APO-B)",
      "ANTI NUCLEAR ANTIBODIES (ANA)",
    ],
    requirements: []
  },
  {
    id: "18",
    title: "Aarogyam X Plus With USTSH",
    description: "Aarogyam X Plus Profile with UTSH is a complete health checkup package of 153 parameters, including vitamin analysis and cardiac risk markers.",
    price: "8469",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Aarogyam X Plus Profile with UTSH is a complete health checkup package of 153 parameters. Along with Complete Urine Analysis + Fasting Blood Sugar analysis, the profile offers complete vitamin analysis. The package helps evaluate Thyroid, Lipid, Liver and Kidney health and also evaluates the health and functioning of the heart (cardiac risk markers) and pancreas. It is a value-for-money package recommended for all age groups. Regular health checkups identify health issues early and enable timely treatment.",
    features: [
      "FASTING BLOOD SUGAR(GLUCOSE)",
      "CHLORIDE",
      "CYSTATIN C",
      "FERRITIN",
      "FRUCTOSAMINE",
      "HOMOCYSTEINE",
      "HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)",
      "INSULIN - FASTING",
      "LIPASE",
      "Lipoprotein (a) [Lp(a)]",
      "MAGNESIUM",
      "LP-PLA2",
      "SERUM COPPER",
      "SERUM ZINC",
      "SODIUM",
      "TESTOSTERONE",
      "ALPHA-1-ANTITRYPSIN (AAT)",
      "VITAMIN A",
      "VITAMIN E",
      "VITAMIN K",  
      "SPECIFIC GRAVITY",
      "APPEARANCE",
      "BACTERIA",
      "URINARY BILIRUBIN",
      "URINE BLOOD",
      "UROBILINOGEN",
      "BILE PIGMENT",
      "BILE SALT",
      "CASTS",
      "COLOUR",
      "CRYSTALS",
      "EPITHELIAL CELLS",
      "URINARY GLUCOSE",
      "URINE KETONE",
      "LEUCOCYTE ESTERASE",
      "URINARY LEUCOCYTES (PUS CELLS)",
      "MUCUS",
      "NITRITE",
      "PARASITE",
      "PH",
      "URINARY PROTEIN",
      "RED BLOOD CELLS",
      "VOLUME",
      "YEAST",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "ANTI CCP (ACCP)",
      "ALKALINE PHOSPHATASE",
      "BILIRUBIN -DIRECT",
      "BILIRUBIN (INDIRECT)",
      "BILIRUBIN - TOTAL",
      "GAMMA GLUTAMYL TRANSFERASE (GGT)",
      "SGOT / SGPT RATIO",
      "SERUM ALB/GLOBULIN RATIO",
      "PROTEIN - TOTAL",
      "ALBUMIN - SERUM",
      "SERUM GLOBULIN",
      "ASPARTATE AMINOTRANSFERASE (SGOT )",
      "ALANINE TRANSAMINASE (SGPT)",
      "SILVER",
      "ALUMINIUM",
      "ARSENIC",
      "BARIUM",
      "BERYLLIUM",
      "BISMUTH",  
      "CADMIUM",
      "COBALT",
      "CHROMIUM",
      "CAESIUM",
      "MERCURY",
      "MANGANESE",
      "MOLYBDENUM",
      "NICKEL",
      "LEAD",
      "ANTIMONY",
      "SELENIUM",
      "TIN",
      "STRONTIUM",
      "THALLIUM",
      "URANIUM",
      "VANADIUM",
      "IRON",
      "% TRANSFERRIN SATURATION",
      "TOTAL IRON BINDING CAPACITY (TIBC)",
      "UNSAT.IRON-BINDING CAPACITY(UIBC)",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "VITAMIN D TOTAL",
      "VITAMIN D2",
      "VITAMIN D3",
      "VITAMIN B-12",
      "VITAMIN B1/THIAMIN",
      "VITAMIN B2/RIBOFLAVIN",
      "VITAMIN B3/NICOTINIC ACID",
      "VITAMIN B5/PANTOTHENIC",
      "VITAMIN B6/PYRIDOXAL - 5 - PHOSPHATE",
      "VITAMIN B7/BIOTIN",
      "VITAMIN B9/FOLIC ACID",
      "TOTAL TRIIODOTHYRONINE (T3)",
      "TOTAL THYROXINE (T4)",
      "TSH - ULTRASENSITIVE",
      "URINARY MICROALBUMIN",
      "URI. ALBUMIN/CREATININE RATIO (UA/C)",
      "CREATININE - URINE",
      "APO B / APO A1 RATIO (APO B/A1)",
      "APOLIPOPROTEIN - A1 (APO-A1)",
      "APOLIPOPROTEIN - B (APO-B)",
      "AMYLASE",
      "ANTI NUCLEAR ANTIBODIES (ANA)",
      "BLOOD KETONE (D3HB)",
    ],
    requirements: []
  },
  {
    id: "19",
    title: "Aarogyam XL Plus with USTSH",
    description: "Aarogyam XL Plus Profile with UTSH is a complete health checkup package of 163 parameters, including steroid profile and crucial hormones.",
    price: "10174",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Aarogyam XL Plus Profile with UTSH is a complete health checkup package of 163 parameters. Along with Complete Urine Analysis + Fasting Blood Sugar analysis, the profile offers steroid profile, including crucial hormones like testosterone and progesterone for men and women, respectively. This helps understand your metabolism, immune functions and sexual health. It is a value-for-money package recommended for all age groups. Regular checkups help in early detection and better management of health issues.",
    features: [
      "FASTING BLOOD SUGAR(GLUCOSE)",
      "CHLORIDE",
      "CYSTATIN C",
      "FERRITIN",
      "FRUCTOSAMINE",
      "HOMOCYSTEINE",
      "HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)",
      "INSULIN - FASTING",
      "LIPASE",
      "Lipoprotein (a) [Lp(a)]",
      "MAGNESIUM",
      "LP-PLA2",
      "SERUM COPPER",
      "SERUM ZINC",
      "SODIUM",
      "ALPHA-1-ANTITRYPSIN (AAT)",
      "VITAMIN A",
      "VITAMIN E",
      "VITAMIN K",
      "SPECIFIC GRAVITY",
      "APPEARANCE",
      "BACTERIA",
      "URINARY BILIRUBIN",
      "URINE BLOOD",
      "UROBILINOGEN",
      "BILE PIGMENT",
      "BILE SALT",
      "CASTS",
      "COLOUR",
      "CRYSTALS",
      "EPITHELIAL CELLS",
      "URINARY GLUCOSE",
      "URINE KETONE",
      "LEUCOCYTE ESTERASE",
      "URINARY LEUCOCYTES (PUS CELLS)",
      "MUCUS",
      "NITRITE",
      "PARASITE",
      "PH",
      "URINARY PROTEIN",
      "RED BLOOD CELLS",
      "VOLUME",
      "YEAST",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "ANTI CCP (ACCP)",
      "ALKALINE PHOSPHATASE",
      "BILIRUBIN -DIRECT",
      "BILIRUBIN (INDIRECT)",
      "BILIRUBIN - TOTAL",
      "GAMMA GLUTAMYL TRANSFERASE (GGT)",
      "SGOT / SGPT RATIO",
      "SERUM ALB/GLOBULIN RATIO",
      "PROTEIN - TOTAL",
      "ALBUMIN - SERUM",
      "SERUM GLOBULIN",
      "ASPARTATE AMINOTRANSFERASE (SGOT )",
      "ALANINE TRANSAMINASE (SGPT)",
      "SILVER",
      "ALUMINIUM",
      "ARSENIC",
      "BARIUM",
      "BERYLLIUM",
      "BISMUTH",
      "CADMIUM",
      "COBALT",
      "CHROMIUM",
      "CAESIUM",
      "MERCURY",
      "MANGANESE",
      "MOLYBDENUM",
      "NICKEL",
      "LEAD",
      "ANTIMONY",
      "SELENIUM",
      "TIN",
      "STRONTIUM",
      "THALLIUM",
      "URANIUM",
      "VANADIUM",
      "IRON",
      "% TRANSFERRIN SATURATION",
      "TOTAL IRON BINDING CAPACITY (TIBC)",
      "UNSAT.IRON-BINDING CAPACITY(UIBC)",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "TROPONIN I HEART ATTACK RISK",
      "VITAMIN D TOTAL",
      "VITAMIN D2",
      "VITAMIN D3",
      "VITAMIN B-12",
      "VITAMIN B1/THIAMIN",
      "VITAMIN B2/RIBOFLAVIN",
      "VITAMIN B3/NICOTINIC ACID",
      "VITAMIN B5/PANTOTHENIC",
      "VITAMIN B6/PYRIDOXAL - 5 - PHOSPHATE",
      "VITAMIN B7/BIOTIN",
      "VITAMIN B9/FOLIC ACID",
      "TOTAL TRIIODOTHYRONINE (T3)",
      "TOTAL THYROXINE (T4)",
      "TSH - ULTRASENSITIVE",
      "URINARY MICROALBUMIN",
      "URI. ALBUMIN/CREATININE RATIO (UA/C)",
      "CREATININE - URINE",
      "APO B / APO A1 RATIO (APO B/A1)",
      "APOLIPOPROTEIN - A1 (APO-A1)",
      "APOLIPOPROTEIN - B (APO-B)",
      "ANDROSTENEDIONE",
      "17-HYDROXYPROGESTERONE",
      "CORTISOL",
      "CORTICOSTERONE",
      "DEOXYCORTISOL",
      "DEHYDROEPIANDROSTERONE",
      "DHEA - SULPHATE (DHEAS)",
      "ESTRADIOL",
      "PROGESTERONE",
      "TESTOSTERONE",
      "AMYLASE",
      "ANTI NUCLEAR ANTIBODIES (ANA)",
      "BLOOD KETONE (D3HB)",
    ],
    requirements: []
  },
  {
    id: "20",
    title: "TOTAL HEALTH PROFILE PLUS",
    description: "",
    price: "1760",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Nil",
    features: [
      "FASTING BLOOD SUGAR(GLUCOSE)",
      "HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)",
      "IRON",
      "VITAMIN B-12",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "ALKALINE PHOSPHATASE",
      "BILIRUBIN -DIRECT",
      "BILIRUBIN (INDIRECT)",
      "BILIRUBIN - TOTAL",
      "GAMMA GLUTAMYL TRANSFERASE (GGT)",
      "SGOT / SGPT RATIO",
      "SERUM ALB/GLOBULIN RATIO",
      "PROTEIN - TOTAL",
      "ALBUMIN - SERUM",
      "SERUM GLOBULIN",
      "ASPARTATE AMINOTRANSFERASE (SGOT )",
      "ALANINE TRANSAMINASE (SGPT)",
      "SPECIFIC GRAVITY",
      "APPEARANCE",
      "URINARY BILIRUBIN",
      "URINE BLOOD",
      "UROBILINOGEN",
      "COLOUR",
      "URINARY GLUCOSE",
      "URINE KETONE",
      "LEUCOCYTE ESTERASE",
      "URINARY LEUCOCYTES (PUS CELLS)",
      "NITRITE",
      "PH",
      "URINARY PROTEIN",
      "VOLUME",
      "CHLORIDE",
      "POTASSIUM",
      "SODIUM",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "VITAMIN D TOTAL",
      "VITAMIN D2",
      "VITAMIN D3",
      "TOTAL TRIIODOTHYRONINE (T3)",
      "TOTAL THYROXINE (T4)",
      "TSH - ULTRASENSITIVE",
    ],
    requirements: []
  },
  {
    id: "21",
    title: "PRE-PREGNANCY PROFILE",
    description: "Pre-Pregnancy Profile helps detect health conditions that may affect pregnancy and is recommended before conception.",
    price: "3168",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Pre-Pregnancy Profile helps detect health conditions that may affect pregnancy. If your customers are planning to conceive and want to ensure optimal health, promote this profile. Pre-pregnancy checkup is also recommended for assessing overall reproductive health before conception. With the help of this test, one can also identify any potential issues that could impact pregnancy and take preventive measures.",
    features: [
      "RANDOM BLOOD SUGAR(GLUCOSE)",
      "HIV I and II",
      "HEPATITIS B SURFACE ANTIGEN (HBSAG)",
      "VDRL (RPR) FOR SYPHILIS",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "RH TYPING",
      "BLOOD GROUPING",
      "SPECIFIC GRAVITY",
      "APPEARANCE",
      "URINARY BILIRUBIN",
      "URINE BLOOD",
      "UROBILINOGEN",
      "COLOUR",
      "URINARY GLUCOSE",
      "URINE KETONE",
      "LEUCOCYTE ESTERASE",
      "URINARY LEUCOCYTES (PUS CELLS)",
      "NITRITE",
      "PH",
      "URINARY PROTEIN",
      "VOLUME",
      "TOTAL TRIIODOTHYRONINE (T3)",
      "TOTAL THYROXINE (T4)",
      "TSH - ULTRASENSITIVE",
      "ANTI HEPATITIS C VIRUS (ANTI HCV) - TOTAL",
    ],
    requirements: []
  },
  {
    id: "22",
    title: "HEALTHY 2025 PACKAGE",
    description: "Healthy 2025 Package is a preventive care routine health checkup package with 114 parameters for routine health monitoring.",
    price: "2025",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Healthy 2025 Package is a preventive care routine health checkup package that includes 114 parameters with essential blood and urine tests for routine health monitoring - liver, lipid, kidney, thyroid, CBC and more. The package is highly recommended for regular health monitoring, even when there are no health issues. One can detect any potential health problems at an early stage and seek right medical treatment at the right time.",
    features: [
      "25-OH VITAMIN D (TOTAL)",
      "VITAMIN B-12",
      "SPECIFIC GRAVITY",
      "APPEARANCE",
      "BACTERIA",
      "URINARY BILIRUBIN",
      "URINE BLOOD",
      "UROBILINOGEN",
      "BILE PIGMENT",
      "BILE SALT",
      "CASTS",
      "COLOUR",
      "CRYSTALS",
      "EPITHELIAL CELLS",
      "URINARY GLUCOSE",
      "URINE KETONE",
      "LEUCOCYTE ESTERASE",
      "URINARY LEUCOCYTES (PUS CELLS)",
      "MUCUS",
      "NITRITE",
      "PARASITE",
      "PH",
      "URINARY PROTEIN",
      "RED BLOOD CELLS",
      "VOLUME",
      "YEAST",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN", 
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "ALKALINE PHOSPHATASE",
      "BILIRUBIN -DIRECT",
      "BILIRUBIN (INDIRECT)",
      "BILIRUBIN - TOTAL",
      "GAMMA GLUTAMYL TRANSFERASE (GGT)",
      "SGOT / SGPT RATIO",
      "SERUM ALB/GLOBULIN RATIO",
      "PROTEIN - TOTAL",
      "ALBUMIN - SERUM",
      "SERUM GLOBULIN",
      "ASPARTATE AMINOTRANSFERASE (SGOT )",
      "ALANINE TRANSAMINASE (SGPT)",
      "SILVER",
      "ALUMINIUM",
      "ARSENIC",
      "BARIUM",
      "BERYLLIUM",
      "BISMUTH",
      "CADMIUM",
      "COBALT",
      "CHROMIUM",
      "CAESIUM",
      "MERCURY",
      "MANGANESE",
      "MOLYBDENUM",
      "NICKEL",
      "LEAD",
      "ANTIMONY",
      "SELENIUM",
      "TIN",
      "STRONTIUM",
      "THALLIUM",
      "URANIUM",
      "VANADIUM",
      "IRON",
      "% TRANSFERRIN SATURATION",
      "TOTAL IRON BINDING CAPACITY (TIBC)",
      "UNSAT.IRON-BINDING CAPACITY(UIBC)",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "TOTAL TRIIODOTHYRONINE (T3)",
      "TOTAL THYROXINE (T4)",
      "TSH - ULTRASENSITIVE",
    ],
    requirements: []
  },
  {
    id: "23",
    title: "JAANCH HEART SCREEN ADVANCED",
    description: "Jaanch Heart Screen Advanced is a comprehensive test to assess heart health, detect early warning signs, and evaluate risk factors.",
    price: "1499",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Jaanch Heart Screen Advanced, a comprehensive test designed to assess your heart health in detail. This package helps detect early warning signs of cardiovascular diseases and evaluates critical risk factors like cholesterol levels and overall heart function. Ideal package for individuals with a family history of heart disease or existing conditions like hypertension, this screening empowers you to take proactive steps for a healthier heart.",
    features: [
      "CHLORIDE",
      "HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)",
      "Lipoprotein (a) [Lp(a)]",
      "SODIUM",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "TROPONIN I HEART ATTACK RISK",
      "APO B / APO A1 RATIO (APO B/A1)",
      "APOLIPOPROTEIN - A1 (APO-A1)",
      "APOLIPOPROTEIN - B (APO-B)",
    ],
    requirements: []
  },
  {
    id: "24",
    title: "JAANCH - DIABETIC Profile - basic",
    description: "Jaanch Diabetic Profile - Basic is a doctor-curated comprehensive health checkup designed for accurate diagnosis and management of diabetes. It mainly checks the health and functioning of the kidneys and heart. Ideal for all ages, it helps in diabetes detection and treatment monitoring.",
    price: "2199",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Jaanch Diabetic Profile - Basic is a doctor-curated comprehensive health checkup designed for accurate diagnosis and management of diabetes at affordable rates. It mainly checks the health and functioning of the kidneys and heart. This package is ideal for people of all ages. It helps in diabetes detection and treatment monitoring.",
    features: [
      "FASTING BLOOD SUGAR(GLUCOSE)",
      "URINARY MICROALBUMIN",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "CHLORIDE",
      "POTASSIUM",
      "SODIUM",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
    ],
    requirements: []
  },
  {
    id: "25",
    title: "JAANCH - DIABETIC Profile - advanced",
    description: "Jaanch Diabetic Profile - Advanced is a doctor-curated health checkup designed for accurate diagnosis and management of diabetes at affordable rates. It mainly assesses the health and functioning of heart and kidneys. It also offers CBC and tests for evaluating levels of essential nutrients and diabetes detection tests. This package is highly recommended for people of all ages to measure, manage and master diabetes.",
    price: "4949",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Jaanch Diabetic Profile - Advanced is a doctor-curated health checkup designed for accurate diagnosis and management of diabetes at affordable rates. It mainly assesses the health and functioning of heart and kidneys. It also offers CBC and tests for evaluating levels of essential nutrients and diabetes detection tests. This package is highly recommended for people of all ages to measure, manage and master diabetes.",
    features: [
      "FASTING BLOOD SUGAR(GLUCOSE)",
      "C-PEPTIDE",
      "FRUCTOSAMINE",
      "HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)",
      "INSULIN - FASTING",
      "LIPASE",
      "Lipoprotein (a) [Lp(a)]",
      "NT-PROBNP",
      "LP-PLA2",
      "URINARY MICROALBUMIN",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "CHLORIDE",
      "POTASSIUM",
      "SODIUM",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "TROPONIN I HEART ATTACK RISK",
      "APO B / APO A1 RATIO (APO B/A1)",
      "APOLIPOPROTEIN - A1 (APO-A1)",
      "APOLIPOPROTEIN - B (APO-B)",
      "AMYLASE",
      "BLOOD KETONE (D3HB)",
    ],
    requirements: []
  },
  {
    id: "25_2",
    title: "AAROGYAM MONSOON BASIC",
    description: "Aarogyam Monsoon Basic with USTSH is designed for the monsoon season, including parameters for routine checkup and timely diagnosis.",
    price: "1154",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "The monsoon season brings in many infections. Prepare to fight health problems with our Aarogyam Monsoon Basic with USTSH. This specially designed profile includes parameters for routine checkup and more tests for healthy monsoon. Give your patients the accurate and timely diagnosis in less than 6 hrs* for correct treatment.",
    features: [
      "CHLORIDE",
      "SODIUM",
      "TSH - ULTRASENSITIVE",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "ALKALINE PHOSPHATASE",
      "BILIRUBIN -DIRECT",
      "BILIRUBIN (INDIRECT)",
      "BILIRUBIN - TOTAL",
      "GAMMA GLUTAMYL TRANSFERASE (GGT)",
      "SGOT / SGPT RATIO",
      "SERUM ALB/GLOBULIN RATIO",
      "PROTEIN - TOTAL",
      "ALBUMIN - SERUM",
      "SERUM GLOBULIN",
      "ASPARTATE AMINOTRANSFERASE (SGOT )",
      "ALANINE TRANSAMINASE (SGPT)",
      "IRON",
      "% TRANSFERRIN SATURATION",
      "TOTAL IRON BINDING CAPACITY (TIBC)",
      "UNSAT.IRON-BINDING CAPACITY(UIBC)",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "25-OH VITAMIN D (TOTAL)",
      "VITAMIN B-12",
    ],
    requirements: []
  },
  {
    id: "26",
    title: "ALLERGY PANEL - FOOD, INHALANT, NON-VEG PLUS DRUG",
    description: "This test helps to know about foods, inhalants and medicines one may be allergic to and provides a comprehensive list of allergens.",
    price: "12300",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "This test helps to know about foods, inhalants and medicines one may be allergic to and provides a comprehensive list of allergens.",
    features: [

    ],
    requirements: []
  },
  {
    id: "27",
    title: "JAANCH THYROID PROFILE - BASIC",
    description: "Jaanch Thyroid Profile - Basic helps detect thyroid disorders and is recommended for those with symptoms or family history.",
    price: "549",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Jaanch Thyroid Profile - Basic helps detect thyroid disorders. If your customer is experiencing symptoms like fatigue, weight changes or mood swings, promote this profile. Thyroid checkup is also recommended for individuals with a family history of thyroid issues. With the help of this test, one can also understand their thyroid function and detect imbalances in time.",
    features: [
      "TOTAL TRIIODOTHYRONINE (T3)",
      "TOTAL THYROXINE (T4)",
      "FREE TRIIODOTHYRONINE (FT3)",
      "FREE THYROXINE (FT4)",
      "TSH - ULTRASENSITIVE",
    ],
    requirements: []
  },
  {
    id: "28",
    title: "JAANCH CANCER SCREENING MALE BASIC",
    description: "Jaanch Cancer Screening Male Basic is a focused diagnostic panel for early detection of cancer in men, including essential cancer marker tests.",
    price: "1299",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "The Jaanch Cancer Screening Male Basic package is a focused diagnostic panel designed to help detect early signs of cancer in men. This package includes essential cancer marker tests such as PSA (Prostate-Specific Antigen) for prostate health assessment, along with CA 19-9 & Carcino Embryonic Antigen (CEA). It is particularly beneficial for individuals with a family history of cancer or those seeking routine screening for early detection.",
    features: [
      "CA 19.9",
      "CARCINO EMBRYONIC ANTIGEN (CEA)",
      "PROSTATE SPECIFIC ANTIGEN (PSA)",
    ],
    requirements: []
  },
  {
    id: "29",
    title: "JAANCH - MENS HAIRFALL SCREENING ADVANCED",
    description: "",
    price: "",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "",
    features: [],
    requirements: []
  },
  {
    id: "30",
    title: "JAANCH - STD PROFILE BASIC",
    description: "Jaanch STD Profile Basic is a doctor-curated 12-parameter package to help detect the cause of sexually transmitted diseases (STDs).",
    price: "2749",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "Jaanch STD Profile Basic is a highly recommended doctor-curated 12-parameter package. It helps detect the cause of sexually transmitted diseases (STDs) accurately at budget-friendly prices. The package includes tests that help identify various types of STDs, like Chlamydia, Syphilis, Herpes, Hepatitis and HIV. This package is ideal for both men and women. Timely diagnosis and treatment of STDs can help lower the risk of any further serious complications.",
    features: [
      "HIV I and II",
      "ANTI CHLAMYDIA ANTIBODY IGG",
      "ANTI CHLAMYDIA ANTIBODY IGM",
      "HEPATITIS B SURFACE ANTIGEN (HBSAG)",
      "VDRL (RPR) FOR SYPHILIS",
      "TREPONEMA PALLIDUM ANTIBODY (TPAB)",
      "TREPONEMA PALLIDUM HAEMAGGLUTINATION",
      "HERPES SIMPLEX VIRUS I (HSV)-IGG",
      "HERPES SIMPLEX VIRUS I (HSV)-IGM",
      "HERPES SIMPLEX VIRUS II (HSV)-IGG",
      "HERPES SIMPLEX VIRUS II (HSV)-IGM",
      "ANTI HEPATITIS C VIRUS (ANTI HCV) - TOTAL",
    ],
    requirements: []
  },
  {
    id: "31",
    title: "Extensive full body health checkup",
    description: "The Extensive Full Body Health Checkup is a comprehensive diagnostic package that evaluates overall health across 127 vital parameters.",
    price: "3399",
    duration: "",
    rating: 0,
    patients: 0,
    isPopular: false,
    category: "",
    imageAlt: "",
    image: "",
    detailedDescription: "The Extensive Full Body Health Checkup is a comprehensive diagnostic package that evaluates overall health across 127 vital parameters, covering essential aspects such as liver, kidney, heart health, thyroid, blood sugar levels, lipid, CBC, vitamin levels, hormonal balance, urine analysis and more. This all-in-one package is designed for proactive health monitoring, early detection of potential diseases and maintaining long-term wellness.",
    features: [
      "FASTING BLOOD SUGAR(GLUCOSE)",
      "CARCINO EMBRYONIC ANTIGEN (CEA)",
      "CHLORIDE",
      "HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)",
      "SPECIFIC GRAVITY",
      "URINARY BILIRUBIN",
      "URINE BLOOD",
      "UROBILINOGEN",
      "URINARY GLUCOSE",
      "URINE KETONE",
      "URINARY LEUCOCYTES (PUS CELLS)",
      "NITRITE",
      "PH",
      "URINARY PROTEIN",
      "LIPASE",
      "Lipoprotein (a) [Lp(a)]",
      "MAGNESIUM",
      "SERUM COPPER",
      "SERUM ZINC",
      "SODIUM",
      " TRANSFERRIN SERUM",
      "VITAMIN A",
      "VITAMIN B-12",
      "VITAMIN B1/THIAMIN",
      "VITAMIN B2/RIBOFLAVIN",
      "VITAMIN B3/NICOTINIC ACID",
      "VITAMIN B5/PANTOTHENIC",
      "VITAMIN B6/PYRIDOXAL - 5 - PHOSPHATE",
      "VITAMIN B7/BIOTIN",
      "VITAMIN B9/FOLIC ACID",
      "VITAMIN E",
      "VITAMIN K",
      "HbA1c",
      "AVERAGE BLOOD GLUCOSE (ABG)",
      "LYMPHOCYTES - ABSOLUTE COUNT",
      "MONOCYTES - ABSOLUTE COUNT",
      "NEUTROPHILS - ABSOLUTE COUNT",
      "BASOPHILS",
      "EOSINOPHILS",
      "HEMOGLOBIN",
      "IMMATURE GRANULOCYTES(IG)",
      "IMMATURE GRANULOCYTE PERCENTAGE(IG%)",
      "TOTAL LEUCOCYTES COUNT (WBC)",
      "LYMPHOCYTE",
      "MEAN CORPUSCULAR HEMOGLOBIN(MCH)",
      "MEAN CORP.HEMO.CONC(MCHC)",
      "MEAN CORPUSCULAR VOLUME(MCV)",
      "MONOCYTES",
      "MEAN PLATELET VOLUME(MPV)",
      "NEUTROPHILS",
      "NUCLEATED RED BLOOD CELLS",
      "NUCLEATED RED BLOOD CELLS %",
      "PLATELETCRIT(PCT)",
      "HEMATOCRIT(PCV)",
      "PLATELET DISTRIBUTION WIDTH(PDW)",
      "PLATELET TO LARGE CELL RATIO(PLCR)",
      "PLATELET COUNT",
      "TOTAL RBC",
      "RED CELL DISTRIBUTION WIDTH (RDW-CV)",
      "BASOPHILS - ABSOLUTE COUNT",
      "RED CELL DISTRIBUTION WIDTH - SD(RDW-SD)",
      "EOSINOPHILS - ABSOLUTE COUNT",
      "ALKALINE PHOSPHATASE",
      "BILIRUBIN -DIRECT",
      "BILIRUBIN (INDIRECT)",
      "BILIRUBIN - TOTAL",
      "GAMMA GLUTAMYL TRANSFERASE (GGT)",
      "SGOT / SGPT RATIO",
      "SERUM ALB/GLOBULIN RATIO",
      "PROTEIN - TOTAL",
      "ALBUMIN - SERUM",
      "SERUM GLOBULIN",
      "ASPARTATE AMINOTRANSFERASE (SGOT )",
      "ALANINE TRANSAMINASE (SGPT)",
      "SILVER",
      "ALUMINIUM",
      "ARSENIC",
      "BARIUM",
      "BERYLLIUM",
      "BISMUTH",
      "CADMIUM",
      "COBALT",
      "CHROMIUM",
      "CAESIUM",
      "MERCURY",
      "MANGANESE",
      "MOLYBDENUM",
      "NICKEL",
      "LEAD",
      "ANTIMONY",
      "SELENIUM",
      "TIN",
      "STRONTIUM",
      "THALLIUM",
      "URANIUM",
      "VANADIUM",
      "IRON",
      "% TRANSFERRIN SATURATION",
      "TOTAL IRON BINDING CAPACITY (TIBC)",
      "UNSAT.IRON-BINDING CAPACITY(UIBC)",
      "BUN / Sr.CREATININE RATIO",
      "BLOOD UREA NITROGEN (BUN)",
      "CALCIUM",
      "CREATININE - SERUM",
      "UREA / SR.CREATININE RATIO",
      "UREA (CALCULATED)",
      "URIC ACID",
      "TOTAL CHOLESTEROL",
      "HDL CHOLESTEROL - DIRECT",
      "HDL / LDL RATIO",
      "LDL CHOLESTEROL - DIRECT",
      "LDL / HDL RATIO",
      "NON-HDL CHOLESTEROL",
      "TC/ HDL CHOLESTEROL RATIO",
      "TRIG / HDL RATIO",
      "TRIGLYCERIDES",
      "VLDL CHOLESTEROL",
      "VITAMIN D TOTAL",
      "VITAMIN D2",
      "VITAMIN D3",
      "TOTAL TRIIODOTHYRONINE (T3)",
      "TOTAL THYROXINE (T4)",
      "TSH - ULTRASENSITIVE",
      "APO B / APO A1 RATIO (APO B/A1)",
      "APOLIPOPROTEIN - A1 (APO-A1)",
      "APOLIPOPROTEIN - B (APO-B)",
      "AMYLASE",
    ],
    requirements: []
  }
];

// For all cards except id: 20, 24, 29
const randomDurations = ["20 min", "25 min", "30 min", "35 min", "40 min"];
let usedRatings = new Set();
let usedPatients = new Set();
initialServices.forEach((service, idx) => {
  if (!["20", "24", "29"].includes(service.id)) {
    // Random rating between 4.5 and 5.0 (1 decimal)
    let rating;
    do {
      rating = +(4.5 + Math.random() * 0.5).toFixed(1);
    } while (usedRatings.has(rating) && usedRatings.size < 5);
    usedRatings.add(rating);
    service.rating = rating;
    // Random patients between 1200 and 3000
    let patients;
    do {
      patients = Math.floor(1200 + Math.random() * 1800);
    } while (usedPatients.has(patients) && usedPatients.size < 10);
    usedPatients.add(patients);
    service.patients = patients;
    // Random duration from the list
    service.duration = randomDurations[idx % randomDurations.length];
  }
});

export const ServiceProvider = ({ children }: { children: ReactNode }) => {
  const [services, setServices] = useState<Service[]>(initialServices);

  useEffect(() => {
    const fetchServices = async () => {
      try {
        const response = await api.get('/thyroid-packages');
        setServices(response.data);
      } catch (error) {
        console.error('Error fetching services:', error);
      }
    };

    fetchServices();
  }, []);

  const addService = (service: Omit<Service, 'id'>) => {
    const newService = {
      ...service,
      id: Date.now().toString()
    };
    setServices(prev => [...prev, newService]);
  };

  const updateService = async (id: string, updatedService: Partial<Service>) => {
    try {
      const response = await api.put(`/service/${id}`, updatedService);
      setServices(prev => prev.map(service =>
        service.id === id ? response.data : service
      ));
    } catch (error) {
      console.error('Error updating service:', error);
    }
  };

  const deleteService = async (id: string) => {
    try {
      await api.delete(`/service/${id}`);
      setServices(prev => prev.filter(service => service.id !== id));
    } catch (error) {
      console.error('Error deleting service:', error);
    }
  };

  const getService = (id: string) => {
    return services.find(service => service.id === id);
  };

  const updateOffer = async (id: string, updatedOffer: Partial<Service>) => {
    try {
      const response = await api.put(`/offers/${id}`, updatedOffer);
      setServices(prev => prev.map(service =>
        service.id === id ? response.data : service
      ));
    } catch (error) {
      console.error('Error updating offer:', error);
    }
  };

  const deleteOffer = async (id: string) => {
    try {
      await api.delete(`/offers/${id}`);
      setServices(prev => prev.filter(service => service.id !== id));
    } catch (error) {
      console.error('Error deleting offer:', error);
    }
  };

  return (
    <ServiceContext.Provider value={{
      services,
      addService,
      updateService,
      deleteService,
      getService,
      updateOffer,
      deleteOffer
    }}>
      {children}
    </ServiceContext.Provider>
  );
};

export const useServices = () => {
  const context = useContext(ServiceContext);
  if (!context) {
    throw new Error('useServices must be used within a ServiceProvider');
  }
  return context;
};
